tasks:
  - init: echo "Replace me with a build script for the project."
    command: echo "Replace me with something that should run on every start, or just
      remove me entirely."

vscode:
  extensions:
    - atb-isep.bamol-lang@0.1.0:URi/NxQCzcnxm2KooO0Pdg==
    - grammarcraft.xtext-lang@0.4.0:cX+XkaGDMoBjLbUhzMQDCg==