/*
 * generated by Xtext 2.12.0
 */
package opt.isep.dsl.puml.ide

import com.google.inject.Guice
import opt.isep.dsl.puml.PumlRuntimeModule
import opt.isep.dsl.puml.PumlStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class PumlIdeSetup extends PumlStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new PumlRuntimeModule, new PumlIdeModule))
	}
	
}
