/*
 * generated by Xtext 2.12.0
 */
package opt.isep.dsl.puml.tests

import com.google.inject.Inject
import opt.isep.dsl.puml.puml.Plantuml
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(PumlInjectorProvider)
class PumlParsingTest {
	@Inject
	ParseHelper<Plantuml> parseHelper
	
	@Test
	def void loadModel() {
		
		val dslText='''
			@startuml class
			abstract class Person {
				
			} 

			class Car 
			{ 
			}

			class Address { 
				
			}
			@enduml
		'''
		
		val result = parseHelper.parse(dslText)
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
		
		/* To test if valid by PlantUML library
		net.sourceforge.plantuml.SourceStringReader reader = new net.sourceforge.plantuml.SourceStringReader(source);
		// Write the first image to "png"
		String desc = reader.outputImage(png).getDescription();
		// Return a null string if no generation	
 		*/
	}
}
