/*
 * generated by Xtext 2.12.0
 */
package opt.isep.dsl.puml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PumlStandaloneSetup extends PumlStandaloneSetupGenerated {

	def static void doSetup() {
		new PumlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
